var articles = [
  "108 North State Street",
  "108 St Georges Terrace",
  "12 Monkeys",
  "16 Cygni Bb",
  "16 Cygni",
  "16 Vayathinile",
  "1872 FA Cup Final",
  "1873 FA Cup Final",
  "1874 FA Cup Final",
  "1876 FA Cup Final",
  "1877 FA Cup Final",
  "1878 FA Cup Final",
  "1885–86 West Bromwich Albion F.C. season",
  "1889–90 Sheffield United F.C. season",
  "1890–91 Sheffield United F.C. season",
  "1891–92 Sheffield United F.C. season",
  "1892–93 Small Heath F.C. season",
  "1893–94 Small Heath F.C. season",
  "1894–95 Small Heath F.C. season",
  "1903–04 Bradford City A.F.C. season",
  "1904 FA Cup Final",
  "1920–21 Burnley F.C. season",
  "1922–23 Nelson F.C. season",
  "1924–25 Nelson F.C. season",
  "1926 FA Cup Final",
  "1933 FA Cup Final",
  "1936 FA Cup Final",
  "1948 Summer Olympics torch relay",
  "1948 Winter Olympics",
  "1953–54 Port Vale F.C. season",
  "1960 Winter Olympics",
  "1966 European Cup Winners' Cup Final",
  "1967 European Cup Final",
  "1967 Football League Cup Final",
  "1967–68 Manchester City F.C. season",
  "1969 FA Cup Final",
  "1973 CECAFA Cup",
  "1973 UEFA Cup Final",
  "1976 UEFA Cup Final",
  "1977 European Cup Final",
  "1978 European Cup Final",
  "1981 European Cup Final",
  "1984 European Cup Final",
  "1984 Intercontinental Cup",
  "1985 European Cup Final",
  "1985 Wales v Scotland football match",
  "1988 Winter Olympics",
  "1989 FA Charity Shield",
  "1991 FA Charity Shield",
  "1991–92 Arsenal F.C. season",
  "1993 FA Charity Shield",
  "1996 Football League Second Division play-off Final",
  "1996 Football League Third Division play-off Final",
  "1996–97 Arsenal F.C. season",
  "1997–98 Arsenal F.C. season",
  "1997–98 Manchester United F.C. season",
  "1998–99 Arsenal F.C. season",
  "1998–99 Manchester United F.C. season",
  "1999 FA Charity Shield",
  "1999 Scottish Challenge Cup Final",
  "1999–2000 Arsenal F.C. season",
  "1999–2000 S.L. Benfica season",
  "2000 CECAFA Cup",
  "2000 Football League Second Division play-off Final",
  "2000 UEFA Cup Final riots",
  "2000 UEFA Cup Final",
  "2000 UEFA Cup semi-final violence",
  "2000–01 Arsenal F.C. season",
  "2001 FA Charity Shield",
  "2001 UEFA Cup Final",
  "2001 UEFA Super Cup",
  "2001: A Space Odyssey (film)|2001: A Space Odyssey (film)",
  "2001–02 Arsenal F.C. season",
  "2002 FA Community Shield",
  "2002 Scottish Challenge Cup Final",
  "2002 UEFA Cup Final",
  "2002–03 Arsenal F.C. season",
  "2003 FA Community Shield",
  "2003 FA Cup Final",
  "2003 Football League Cup Final",
  "2003–04 Arsenal F.C. season",
  "2004 FA Community Shield",
  "2005 FA Community Shield",
  "2005 FIFA Club World Championship Final",
  "2005 UEFA Champions League Final",
  "2005 UEFA Super Cup",
  "2005–06 Arsenal F.C. season",
  "2006 CECAFA Cup",
  "2006 FA Community Shield",
  "2006 FA Cup Final",
  "2006 UEFA Champions League Final",
  "2006–07 Bristol Rovers F.C. season",
  "2007 Football League Cup Final",
  "2007 Scottish Challenge Cup Final",
  "2007 UEFA Champions League Final",
  "2007–08 Arsenal F.C. season",
  "2007–08 Bradford City A.F.C. season",
  "2007–08 Sunderland A.F.C. season",
  "2008 Summer Olympics",
  "2008 UEFA Champions League Final",
  "2008–09 York City F.C. season",
  "2009 Football League Two play-off Final",
  "2009 UEFA Champions League Final",
  "2009–10 Plymouth Argyle F.C. season",
  "2009–10 York City F.C. season",
  "2010–11 York City F.C. season",
  "2011 FA Cup Final",
  "2011–12 Sheffield United F.C. season",
  "2011–12 York City F.C. season",
  "2012 FA Cup Final",
  "2012 Football League Cup Final",
  "2012 Scottish Cup Final",
  "2012 Summer Olympics opening ceremony",
  "2012 Summer Paralympics",
  "2012–13 York City F.C. season",
  "2013 CECAFA Cup",
  "2013–14 Norwich City F.C. season",
  "2013–14 York City F.C. season",
  "2014 Coppa Italia Final",
  "2014 FA Community Shield",
  "2014–15 York City F.C. season",
  "2015 Football League Cup Final",
  "32 Old Slip",
  "34 Montagu Square, Marylebone",
  "River North Point",
  "47 Ursae Majoris b",
  "47 Ursae Majoris c",
  "47 Ursae Majoris",
  "55 Cancri b",
  "55 Cancri c",
  "55 Cancri d",
  "55 Cancri e",
  "55 Cancri f",
  "55 Cancri",
  "5th Avenue Theatre",
  "61 Cygni",
  "901 New York Avenue",
  "A Bug's Life",
  "A Hard Day's Night (film)|A Hard Day's Night (film)",
  "A Month in the Country (film)|A Month in the Country (film)",
  "A Perfect Circle",
  "A Simple Plan (film)|A Simple Plan (film)",
  "A View to a Kill",
  "A.F.C. Sudbury",
  "AT&T Plaza",
  "Aalborg",
  "Aarhus",
  "Abantiades latipennis",
  "Abby Wambach|Wambach, Abby",
  "Abelisauridae",
  "Aberdaron",
  "Aberdeen F.C.",
  "Abou Diaby|Diaby, Abou",
  "Abyssal plain",
  "Acer rubrum",
  "Adam Clayton|Clayton, Adam",
  "Adam Levine|Levine, Adam",
  "Adam Miller (footballer)|Miller, Adam",
  "Adam Smith (footballer, born February 1985)",
  "Adam Stansfield|Stansfield, Adam",
  "Adams River (British Columbia)",
  "Adamussium",
  "Addax",
  "Adenosine triphosphate",
  "Adlington Hall",
  "Adolf Anderssen|Anderssen, Adolf",
  "Adrian Crowley|Crowley, Adrian",
  "Adriatic Sea",
  "Aerodramus",
  "Aerosmith",
  "Aetosaur",
  "Afrasia djijidae",
  "Agathaeromys",
  "Agkistrodon piscivorus",
  "Agnez Mo",
  "Agustín Ross Cultural Centre",
  "Aker Stadion",
  "Akodon caenosus",
  "Akshardham (Delhi)",
  "Alabama (band)",
  "Aladdin (1992 Disney film)|Aladdin (1992 film)",
  "Alamogordo, New Mexico",
  "Alan Julian|Julian, Alan",
  "Alan Shearer|Shearer, Alan",
  "Alatskivi Castle",
  "Albany City Hall",
  "Albany, New York",
  "Albert Bonass|Bonass, Albert",
  "Alcatraz Federal Penitentiary",
  "Alconétar Bridge",
  "Aldermaston",
  "Alejandro Sanz|Sanz, Alejandro",
  "Aleksandar Đurić",
  "Alesha Dixon|Dixon, Alesha",
  "Alex Lawless|Lawless, Alex",
  "Alex Rhodes (footballer)|Rhodes, Alex",
  "Alexander Alekhine|Alekhine, Alexander",
  "Alfred Lennon|Lennon, Alfred",
  "Algo Centre Mall",
  "Algol",
  "Algonquin Hotel",
  "Ali Hewson|Hewson, Ali",
  "Alien (film)|Alien (film)",
  "Alien: Resurrection",
  "Aliens (film)|Aliens (film)",
  "Alioramus",
  "Alligator gar",
  "Alnus glutinosa",
  "Aloe vera",
  "Alou Diarra|Diarra, Alou",
  "Alpha Andromedae",
  "Alphastates",
  "Alpine ibex",
  "Altair",
  "Altes Stadthaus, Berlin",
  "Altes Stadthaus, Bonn",
  "Althorp",
  "Amak Volcano",
  "Amaranthus brownii",
  "Amargasaurus",
  "Amarillo, Texas",
  "Amber Room",
  "Ambrosden",
  "Ambulance",
  "American Gothic House",
  "American Graffiti",
  "American Samoa at the 2008 Summer Olympics",
  "American Thermos Bottle Company Laurel Hill Plant",
  "American alligator",
  "American bullfrog",
  "American crow",
  "American kestrel",
  "American robin",
  "Americana (film)|Americana (film)",
  "Amino acid",
  "Ammonia fuming",
  "Amon Tobin|Tobin, Amon",
  "Amos Lee|Lee, Amos",
  "Ampelosaurus",
  "Amphicoelias",
  "Amy Winehouse|Winehouse, Amy",
  "An Unforgettable Summer",
  "Anatomy",
  "Anbe Vaa",
  "Andean cock-of-the-rock",
  "Andorra national football team",
  "Andover F.C.",
  "Andre Boucaud|Boucaud, Andre",
  "Andrea Corr|Corr, Andrea",
  "Andreacarus voalavo",
  "Andreas Tegström",
  "Andrei Rublev (film)|Andrei Rublev (film)",
  "Andrew Crofts (footballer)|Crofts, Andrew",
  "Andromeda Galaxy",
  "André Messager",
  "Andy Hessenthaler|Hessenthaler, Andy",
  "Andy Reid (Irish footballer)",
  "Anggun",
  "Anglo-Italian Cup",
  "Animal House|National Lampoon's Animal House",
  "Animal coloration",
  "Animal navigation",
  "Animal testing",
  "Aniru Conteh|Conteh, Aniru",
  "Anna Bågenholm",
  "Annelid",
  "Annie (Norwegian singer)",
  "Annie Hall",
  "Antestor",
  "Anthony Field|Field, Anthony",
  "Anti-predator adaptation",
  "Antibody",
  "Antigua and Barbuda at the 2008 Summer Olympics",
  "Antonio Paoli|Paoli, Antonio",
  "Antonín Kinský",
  "Aonchotheca forresteri",
  "Apatosaurus",
  "Apeomyoides",
  "Aposematism",
  "Apt Pupil (film)|Apt Pupil (film)",
  "Aransas Bay",
  "Arbroath",
  "Arcade Fire",
  "Archaeamphora",
  "Archery at the 2004 Summer Olympics",
  "Architecture in early modern Scotland",
  "Architecture in modern Scotland",
  "Architecture of Denmark",
  "Architecture of Leeds",
  "Architecture of Madagascar",
  "Architecture of Norway",
  "Architecture of Scotland in the Middle Ages",
  "Architecture of Scotland in the Prehistoric era",
  "Architecture of Scotland in the Roman era",
  "Architecture of Scotland",
  "Architecture of the Song dynasty",
  "Arctic Monkeys",
  "Arena Corinthians",
  "Argentodites",
  "Arjen Robben|Robben, Arjen",
  "Arp2/3 complex",
  "Arsenal F.C. in European football",
  "Arsenal Stadium",
  "Arsène Wenger",
  "Art Farmer|Farmer, Art",
  "Art's Auto",
  "Arthropod",
  "Arthur Bell (footballer)|Bell, Arthur",
  "Arthur Sullivan|Sullivan, Arthur",
  "Aruba at the 2004 Summer Olympics",
  "Aruba at the 2008 Summer Olympics",
  "As I Lay Dying (band)",
  "Ashford, Kent",
  "Ashland Mill Bridge",
  "Ashland, Oregon",
  "Ashot Nadanian|Nadanian, Ashot",
  "Ashton Court",
  "Asian house martin",
  "Asplenium bradleyi",
  "Aspmyra Stadion",
  "Astley, Greater Manchester",
  "Astronomical Observatory (University of Illinois at Urbana-Champaign)",
  "Atherton, Greater Manchester",
  "Atlanta",
  "Atlantic blue marlin",
  "Atlantic torpedo",
  "Attalea (palm)|Attalea (genus)",
  "Augie March",
  "Australia 31–0 American Samoa",
  "Australia at the 2014 Winter Paralympics",
  "Australia women's national wheelchair basketball team at the 2012 Summer Paralympics",
  "Australian Crawl",
  "Australian ringneck",
  "Australian blacktip shark",
  "Australian swellshark",
  "Australian weasel shark",
  "Aval Appadithan",
  "Avery Point Light",
  "Avery–MacLeod–McCarty experiment",
  "Avon Gorge",
  "Avril Lavigne|Lavigne, Avril",
  "Axial Seamount",
  "Axl Rose|Rose, Axl",
  "Azerbaijan",
  "Azure-hooded jay",
  "BBC Symphony Orchestra",
  "Back to the Future",
  "Bacliff, Texas",
  "Badajoz",
  "Badrinath Temple",
  "Bahamas at the 2008 Summer Olympics",
  "Bahrain",
  "Balaur bondoc",
  "Ballard Carnegie Library",
  "Banagher",
  "Banded archerfish",
  "Banded houndshark",
  "Bank Street (football ground)",
  "Banksia acanthopoda",
  "Banksia oligantha",
  "Barbados at the 2008 Summer Olympics",
  "Barend Joseph Stokvis|Stokvis, Barend Joseph",
  "Barndoor skate",
  "Barrington Civic Center Historic District",
  "Barrington Court",
  "Barry Cogan (footballer)|Cogan, Barry",
  "Barry Fuller|Fuller, Barry",
  "Basehead",
  "Basin, Montana",
  "Basingstoke",
  "Bass Maltings, Sleaford",
  "Bath Assembly Rooms",
  "Baths of Zeuxippus",
  "Batman & Robin (film)|Batman & Robin (film)",
  "Batman (1989 film)|Batman (1989 film)",
  "Batman Forever",
  "Batman Returns",
  "Batman: Mask of the Phantasm",
  "Batrachotomus",
  "Battle of Old Trafford",
  "Beaded lizard",
  "Beatty, Nevada",
  "Beaumont House",
  "Beauty and the Beast (1991 film)|Beauty and the Beast (1991 film)",
  "Beck",
  "Bee",
  "Beechwood (Vanderlip mansion)",
  "Bees and toxic chemicals",
  "Beetlejuice",
  "Belgium national football team",
  "Belize at the 2008 Summer Olympics",
  "Bell X1 (band)",
  "Bellaire, Texas",
  "Megachile campanulae",
  "Ben Amos|Amos, Ben",
  "Ben May|May, Ben",
  "Ben Nevis",
  "Ben Starosta|Starosta, Ben",
  "Bengal slow loris",
  "Benin at the 2008 Summer Olympics",
  "Benjamin Church House (Bristol, Rhode Island)",
  "Benjamin Ogle Tayloe House",
  "Benjaminville Friends Meeting House and Burial Ground",
  "Bentworth",
  "Bermuda at the 2008 Summer Olympics",
  "Bert Jansch|Jansch, Bert",
  "Beta Pictoris",
  "Betula pendula",
  "Beyoncé",
  "Bianca Ryan|Ryan, Bianca",
  "Białystok",
  "Big Bang (South Korean band)",
  "Bigeye sand tiger",
  "Bigeye thresher",
  "Bigfin reef squid",
  "Bignose shark",
  "Bill Shankly|Shankly, Bill",
  "Bill Szymczyk|Szymczyk, Bill",
  "Billy Bremner",
  "Billy Liddell|Liddell, Billy",
  "Billy Meredith|Meredith, Billy",
  "Billy Talent",
  "Biology",
  "Bioluminescence",
  "Bird collections",
  "Bird migration",
  "Birmingham City F.C.",
  "Birmingham",
  "Bishop's Palace, Wells",
  "Bitis arietans",
  "Gaboon viper",
  "Black Country Communion",
  "Black Creek (Susquehanna River)",
  "Black honeyeater",
  "Black Lab",
  "Black Sabbath (film)|Black Sabbath",
  "Black Sabbath",
  "Black bean aphid",
  "Black catbird",
  "Black dogfish",
  "Black drongo",
  "Black mamba",
  "Black wildebeest",
  "Black-headed sugar ant",
  "Black-shouldered kite",
  "Black-tailed jackrabbit",
  "Black-throated blue warbler",
  "Black-throated gray warbler",
  "Blackdown Hills",
  "Blackford County Courthouse",
  "Blackford County, Indiana",
  "Blackledge River Railroad Bridge",
  "Blackmouth catshark",
  "Blacknose shark",
  "Blackstone Library",
  "Blacktip reef shark",
  "Blacktip shark",
  "Bleeding Through",
  "Blink-182",
  "Bloc Party",
  "Blotchy swellshark",
  "Blue Velvet (film)|Blue Velvet (film)",
  "Blue wildebeest",
  "Bluespotted ribbontail ray",
  "Bluespotted stingray",
  "Bluntnose stingray",
  "Blur (band)",
  "Bob Marley|Marley, Bob",
  "Bobby Fischer|Fischer, Bobby",
  "Bobby Timmons|Timmons, Bobby",
  "Boden Fortress",
  "Body Count",
  "Bohor reedbuck",
  "Bolshoy Ice Dome",
  "Bolton Wanderers F.C.",
  "Bolton",
  "Bonded by Blood (band)",
  "Bootham Crescent",
  "Boredoms",
  "Bornean slow loris",
  "Borneo shark",
  "Botanical garden",
  "Botany",
  "Bottlenose dolphin",
  "Boughton Monchelsea Place",
  "Bound (1996 film)|Bound (1996 film)",
  "Bournemouth",
  "Bowfin",
  "Bowie Seamount",
  "Bowmouth guitarfish",
  "Boys Don't Cry (film)|Boys Don't Cry (film)",
  "Boys in the Sand",
  "Brachiopod",
  "Brachytarsomys mahajambaensis",
  "Brad Mehldau|Mehldau, Brad",
  "Bradwall",
  "Brain",
  "Brainard Homestead State Park",
  "Bramble shark",
  "Brand New (band)",
  "Bratislava",
  "Brazil v Germany (2014 FIFA World Cup)",
  "Breaking Benjamin",
  "Brean Down",
  "Brian Epstein|Epstein, Brian",
  "Briar Creek (Susquehanna River)",
  "Bridgeport Harbor Light",
  "Bridgwater",
  "Brighton Forum",
  "Briskeby Arena",
  "Brislington House",
  "Bristol Rovers F.C.",
  "Bristol",
  "British Library",
  "British Virgin Islands at the 2008 Summer Olympics",
  "Britney Spears|Spears, Britney",
  "Broadway Hollywood Building",
  "Brolga",
  "Brooke Street Pier",
  "Brooks & Dunn",
  "Brown honeyeater",
  "Brown thrasher",
  "Bruce Dickinson|Dickinson, Bruce",
  "Brunei",
  "Bruno Mars|Mars, Bruno",
  "Bruton Dovecote",
  "Bryozoa",
  "Budapest Gambit",
  "Buena Vista Social Club",
  "Bughouse chess",
  "Bugun liocichla",
  "Buildings and architecture of Bath",
  "Bulgaria",
  "Bullet for My Valentine",
  "Bumblebee",
  "Burnham Pavilions",
  "Burnham-on-Sea",
  "Burns, Oregon",
  "Burundi women's national football team",
  "Buster Smith|Smith, Buster",
  "Butthole Surfers",
  "Buxbaumia",
  "Byne's disease",
  "Byzantine (band)",
  "Cactus",
  "Caenorhabditis elegans",
  "Cake (band)",
  "Calais",
  "Caldas da Rainha",
  "California sea lion",
  "California spiny lobster",
  "Camak House",
  "Cambodia women's national football team",
  "Camouflage",
  "Campbell's dwarf hamster",
  "Cancer pagurus",
  "Canidae",
  "Cannons (house)",
  "Canterbury Castle (Portland, Oregon)",
  "Canterbury",
  "Cape Fear shiner",
  "Cape Moreton Light",
  "Cape Verde at the 2008 Summer Olympics",
  "Cape Verde at the 2012 Summer Olympics",
  "Cape lobster",
  "Cape sparrow",
  "Capella",
  "Capesthorne Hall",
  "Capon Lake Whipple Truss Bridge",
  "Caprella mutica",
  "Capybara",
  "Carancahua Bay",
  "Carcinus maenas",
  "Care Bears Movie II: A New Generation",
  "Carex binervis",
  "Caribbean reef shark",
  "Carl Michael Bellman|Bellman, Carl Michael",
  "Carletonomys",
  "Carli Lloyd|Lloyd, Carli",
  "Carlton Hill, Brighton",
  "Carolina wren",
  "Carr Hill",
  "Casa de Estudillo",
  "Casino Royale (1967 film)|Casino Royale (1967 film)",
  "Castle Lake (California)",
  "Castle Park, Bristol",
  "Castles and Town Walls of King Edward in Gwynedd",
  "Castles in Great Britain and Ireland",
  "Cathy Davey|Davey, Cathy",
  "Cavalera Conspiracy",
  "Cave Junction, Oregon",
  "Cayman Islands at the 2008 Summer Olympics",
  "Cedric Wright|Wright, Cedric",
  "Celilo Falls",
  "Celtic Park",
  "Central African Republic at the 2008 Summer Olympics",
  "Central African Republic women's national football team",
  "Central American squirrel monkey",
  "Central Park (skyscraper)",
  "Centre Square (Building)",
  "Cephalic Carnage",
  "Ceratopsia",
  "Cervix",
  "Cesc Fàbregas",
  "Cetiosauriscus",
  "Chacma baboon",
  "Chad at the 2008 Summer Olympics",
  "Chalke",
  "Chambersburg, Pennsylvania",
  "Chamois Niortais F.C.",
  "Chana School",
  "Chard, Somerset",
  "Charles Frederick Horn|Horn, Charles Fredrick",
  "Charles Payne House",
  "Chase Promenade",
  "Chatteris",
  "Ched Evans|Evans, Ched",
  "Cheddar Gorge",
  "Cheddar, Somerset",
  "Chelicerata",
  "Cherry Poppin' Daddies",
  "Chess in Armenia",
  "Chester Rows",
  "Chestnut sparrow",
  "Chevelle (band)",
  "Chew Magna",
  "Chicago Spire",
  "Chicago Theatre",
  "Chicago bid for the 2016 Summer Olympics",
  "Chief Keef",
  "Chimes at Midnight",
  "Chiming Fountain",
  "China",
  "Chiprovtsi",
  "Chirocephalus diaphanus",
  "Chitinozoan",
  "Chittenango ovate amber snail",
  "Chlamys hastata",
  "Cholmondeley Castle",
  "Chough",
  "Chris Beardsley|Beardsley, Chris",
  "Chris Brandon|Brandon, Chris",
  "Chris Carruthers|Carruthers, Chris",
  "Chris Holroyd|Holroyd, Chris",
  "Chris Smith (footballer, born 1981)",
  "Christchurch, Dorset",
  "Christina Milian|Milian, Christina",
  "Chrome Division",
  "Chrysler Building",
  "Chuck Berry|Berry, Chuck",
  "Churche's Mansion",
  "Château de Verteuil, Charente",
  "Cibolo Creek",
  "Cicuta",
  "Cillian Sheridan|Sheridan, Cillian",
  "Cine City, Withington",
  "Circular permutation in proteins",
  "Citadel of Erbil",
  "Citadel of Damascus",
  "City of Salford",
  "Citygarden",
  "Clara Clemens|Clemens, Clara",
  "Clarke Carlisle|Carlisle, Clarke",
  "Clay Walker|Walker, Clay",
  "Clayton Donaldson|Donaldson, Clayton",
  "Cleaning symbiosis",
  "Clevedon Court",
  "Clevedon Pier",
  "Clevedon",
  "Cliff Burton|Burton, Cliff",
  "Cliff Williams|Williams, Cliff",
  "Clint Black|Black, Clint",
  "Clinton Street Theater",
  "Clitoris",
  "Close Encounters of the Third Kind",
  "Cloudinid",
  "Cloudy catshark",
  "Cluj-Napoca",
  "Cnidaria",
  "Coatbridge",
  "Coconut crab",
  "Coelurus",
  "Coffin ray",
  "Coldplay",
  "Colin Doyle (footballer)|Doyle, Colin",
  "Collared brown lemur",
  "College of All Saints, Maidstone",
  "Colony collapse disorder",
  "Colross",
  "Columbia, Missouri",
  "Comcast Center (Philadelphia)",
  "Commelina communis",
  "Commerce Square",
  "Common eland",
  "Common stingray",
  "Common thresher",
  "Common torpedo",
  "Common vampire bat",
  "Community Trolls",
  "Confederate Memorial (Romney, West Virginia)",
  "Congo serpent eagle",
  "Connie Smith|Smith, Connie",
  "Constitution Center (Washington, D.C.)",
  "Contact (1997 American film)|Contact (1997 US film)",
  "Convict cichlid",
  "Cook Islands at the 2008 Summer Olympics",
  "Cookiecutter shark",
  "Cool Hand Luke",
  "Cool World",
  "Cooper, Texas",
  "Copa Libertadores",
  "Copano Bay",
  "Copper shark",
  "Coquitlam",
  "Coral Springs, Florida",
  "Coral catshark",
  "Coral",
  "Cordyline australis",
  "Corey Taylor|Taylor, Corey",
  "Cornelius P. Rhoads|Rhoads, Cornelius P.",
  "Corpus Christi Bay",
  "Cortina d'Ampezzo",
  "Corythosaurus",
  "Cotton-top tamarin",
  "Council House, Perth",
  "Countershading",
  "Country Joe and the Fish",
  "County Borough of Leeds",
  "Courtney Love|Love, Courtney",
  "Crabble Athletic Ground",
  "Crag martin",
  "Craig McAllister|McAllister, Craig",
  "Craig Nelthorpe|Nelthorpe, Craig",
  "Craig Taborn|Taborn, Craig",
  "Craigiehall",
  "Cranham",
  "Cranial nerves",
  "Crass",
  "Crater Lake",
  "Crawley",
  "Creek whaler",
  "Crested auklet",
  "Crested shelduck",
  "Crewe Hall",
  "Crewkerne",
  "Crex",
  "Cricket (insect)",
  "Crimewave",
  "Croatia national football team",
  "Croatia",
  "Croatian Littoral",
  "Crocodile shark",
  "Crossback stingaree",
  "Crossroads to Crime",
  "Crustacean",
  "Cryolophosaurus",
  "Crystal Palace Dinosaurs",
  "Crystal Palace F.C.",
  "Crystal Palace, London",
  "Ctenophora",
  "Ctenosaura bakeri",
  "Cubeb",
  "Cubzac-les-Ponts",
  "Cullompton",
  "Cultivar",
  "Cultivated plant taxonomy",
  "Cunard Building",
  "Curtis Woodhouse|Woodhouse, Curtis",
  "Curve-billed thrasher",
  "Cushing House",
  "Cuvier's dwarf caiman",
  "Cwm, Llanrothal",
  "Cylindropuntia imbricata",
  "Cynthia Lennon|Lennon, Cynthia",
  "Cytosol",
  "D.C. United",
  "DJ Kool Herc",
  "Daara J",
  "Russell's viper",
  "Daft Punk",
  "Daicon III and IV Opening Animations|Daicon III and IV Opening Animations",
  "Dal Lake",
  "Daniel McBreen|McBreen, Daniel",
  "Daniel S. Schanck Observatory",
  "Daniel Santos (singer)|Santos, Daniel (singer)",
  "Danny Parslow|Parslow, Danny",
  "Danube crested newt",
  "Darby Creek (Pennsylvania)",
  "Darius Charles|Charles, Darius",
  "Dark shyshark",
  "Darlington F.C.",
  "Darren Bent|Bent, Darren",
  "Darren Middleton|Middleton, Darren",
  "Dartford Crossing",
  "Datchet Bridge",
  "Davenport, Iowa",
  "David Archuleta|Archuleta, David",
  "David Beharall|Beharall, David",
  "David Bridges|Bridges, David",
  "David Hamilton (footballer)|Hamilton, David",
  "David Hattner|Hattner, David",
  "David Johnson (footballer, born 1976)",
  "David L. Cook|Cook, David L.",
  "David Lucas (composer)|Lucas, David (composer)",
  "David McGurk|McGurk, David",
  "David Villa|Villa, David",
  "David Wetherall|Wetherall, David",
  "Davidson Seamount",
  "Dayton, Ohio",
  "De Akkermolen",
  "Death Cab for Cutie",
  "Death of John Lennon",
  "Decapitated (band)",
  "DecembeRadio",
  "Deckham",
  "Decline in amphibian populations",
  "Deepwater stingray",
  "Defeated Sanity",
  "Deimatic behaviour",
  "Delorentos",
  "Delta County Courthouse",
  "Denmark Street",
  "Dennis Bergkamp|Bergkamp, Dennis",
  "Denver",
  "Depot Town",
  "Deptford",
  "Derek Webb|Webb, Derek",
  "Destiny's Child",
  "DevilDriver",
  "Devin Townsend|Townsend, Devin",
  "Devourment",
  "Diamond Valley Lake",
  "Diamond stingray",
  "Diamonds Are Forever (film)|Diamonds Are Forever (film)",
  "Dick Tracy (1990 film)|Dick Tracy (1990 film)",
  "Didsbury",
  "Diego Costa|Costa, Diego",
  "Dimetrodon",
  "Dinheirosaurus",
  "Dirty Dancing",
  "Disruptive coloration",
  "Ditton, Kent",
  "Divine Heresy",
  "Djibouti francolin",
  "Djibouti women's national football team",
  "Djibril Cissé",
  "Djungarian hamster",
  "Dolphinarium",
  "Dolphinarium",
  "Dominant white",
  "Dominica at the 2008 Summer Olympics",
  "Don Revie|Revie, Don",
  "Don't Look Now",
  "Doppelgänger (1969 film)",
  "Dorian Holley|Holley, Dorian",
  "Dorival Caymmi|Caymmi, Dorival",
  "Doro (musician)",
  "Doug Anthony All Stars",
  "Doug Stone|Stone, Doug",
  "Dovecot at Blackford Farm",
  "Down (band)",
  "Down and Dirty Duck",
  "Dr. Dre",
  "Dr. No (film)|Dr. No (film)",
  "Dromaeosauridae",
  "Dromedary",
  "Drosera anglica",
  "Drosera",
  "Duane Courtney|Courtney, Duane",
  "Dugong",
  "Dumas Brothel",
  "Dundee United F.C.",
  "Dunham Massey",
  "Dunkery Hill",
  "Dunrobin Castle",
  "Dunster Working Watermill",
  "Dunster",
  "Dusky crag martin",
  "Dusky woodswallow",
  "Dusky dolphin",
  "Dusky shark",
  "Dutch brick",
  "Dyspanopeus sayi",
  "Early skyscrapers",
  "Earthsuit",
  "Earwig",
  "East Riding of Yorkshire",
  "East Stirlingshire F.C.",
  "East Worldham",
  "Eastbourne",
  "Easter Road",
  "Eastern green mamba",
  "Eastern mole",
  "Eaton Hall, Cheshire",
  "Eazy-E",
  "Ebbor Gorge",
  "Ebenezer Avery House",
  "Eccles, Greater Manchester",
  "Ecnomiohyla rabborum",
  "Ecology",
  "Ed Wood (film)|Ed Wood (film)",
  "Eddie Bayers|Bayers, Eddie",
  "Eddie Costa|Costa, Eddie",
  "Eddie Johnson (English footballer)|Johnson, Eddie",
  "Eden Hazard|Hazard, Eden",
  "Edinburgh Place Ferry Pier",
  "Editors (band)",
  "Edmonton",
  "Edward Scissorhands",
  "Egardus",
  "Egyptian vulture",
  "Ekbletomys",
  "El Salvador national football team",
  "Eli Todd|Todd, Eli",
  "Eliel Saarinen's Tribune Tower design",
  "Eliurus petteri",
  "Ellwood House",
  "Elmo Tanner|Tanner, Elmo",
  "Elmwood (Cambridge, Massachusetts)",
  "Ely, Cambridgeshire",
  "Emanuel Lasker|Lasker, Emanuel",
  "Emile Heskey|Heskey, Emile",
  "Emilie Autumn|Autumn, Emilie",
  "Eminem",
  "Empire of the Sun (film)|Empire of the Sun (film)",
  "En passant",
  "Endgame tablebase",
  "Endomembrane system",
  "England",
  "Entoprocta",
  "Entranceway at Main Street at Roycroft Boulevard",
  "Entranceways at Main Street at Lamarck Drive and Smallwood Drive",
  "Epaulette shark",
  "Epsilon Aurigae",
  "Equine nutrition",
  "Equus (genus)|Equus (genus)",
  "Erik Chisholm|Chisholm, Erik",
  "Eriophorum angustifolium",
  "Ernie Cooksey|Cooksey, Ernie",
  "Esbjerg",
  "Escape from New York",
  "Esham",
  "Estate houses in Scotland",
  "Estuary stingray",
  "Eurasian eagle-owl",
  "Eurasian sparrowhawk",
  "Eurasian wryneck",
  "Europa Point Lighthouse",
  "European Nucleotide Archive",
  "European hare",
  "European polecat",
  "European robin",
  "Eva Cassidy|Cassidy, Eva",
  "Evan O'Neill Kane|Kane, Evan O'Neill",
  "Evanton",
  "Everglades",
  "Evermore (band)",
  "Exmoor pony",
  "External morphology of Lepidoptera",
  "Eyes Without a Face",
  "F.C. United of Manchester",
  "FC Bayern Munich",
  "FIFA World Cup Trophy",
  "Falkner Island Light",
  "Falkner Island",
  "False catshark",
  "Fandi Ahmad|Ahmad, Fandi",
  "Fat Freddy's Drop",
  "Fatimid architecture",
  "Faversham",
  "Feeder",
  "Felix Mendelssohn|Mendelssohn, Felix",
  "Felling, Tyne and Wear",
  "Feminist Improvising Group",
  "FernGully: The Last Rainforest",
  "Fernando Torres|Torres, Fernando",
  "Ferris Bueller's Day Off",
  "Fieldfare",
  "Fifth Ward Wardroom",
  "Fight Like Apes",
  "Finetooth shark",
  "Fire Station No. 23 (Los Angeles, California)",
  "Fire Station No. 4 (Pawtucket, Rhode Island)",
  "First Ward Wardroom",
  "Fish",
  "Fisher (animal)",
  "Fishing Creek (North Branch Susquehanna River)",
  "Five Finger Death Punch",
  "Five Mile Point Light",
  "Flagstaff, Arizona",
  "Flammulated flycatcher",
  "Flatworm",
  "Flixton, Greater Manchester",
  "Flora of Scotland",
  "Florida mouse",
  "Football in the Philippines",
  "For Your Eyes Only (film)|For Your Eyes Only (film)",
  "Foramen spinosum",
  "Forbidden City",
  "Forbidden Zone",
  "Forest cobra",
  "Forglen House",
  "Forrest Gump",
  "Fort Al Jalali",
  "Fort Dansborg",
  "Fort Greble",
  "Fort Lauderdale, Florida",
  "Fort Pasir Panjang",
  "Fort Wayne, Indiana",
  "Forth Valley Royal Hospital",
  "Fortress of Klis",
  "Fossil Creek",
  "Foster-Payne House",
  "Fraizer Campbell|Campbell, Fraizer",
  "Frances Ames|Ames, Frances",
  "Frances McConnell-Mills|McConnell-Mills, Frances",
  "Frances Oldham Kelsey|Kelsey, Frances Oldham",
  "Franck Ribéry",
  "Frank Swift|Swift, Frank",
  "Franklin Center (Chicago)",
  "Franz Burgmeier|Burgmeier, Franz",
  "Fraser Mansion",
  "Freddie Mercury|Mercury, Freddie",
  "Frederik Magle|Magle, Frederik",
  "Frilled shark",
  "Frog battery",
  "From Autumn to Ashes",
  "From Russia with Love (film)|From Russia with Love (film)",
  "Frome",
  "Frost Bank Tower",
  "Fulfordgate",
  "Fuller Houses",
  "Fur-bearing trout",
  "G-Dragon",
  "G-spot",
  "Gliese 3634 b",
  "GJ 3634",
  "Galactic habitable zone",
  "Galapagos shark",
  "Galveston Bay Area",
  "Galveston, Texas",
  "Gambia women's national football team",
  "Game 39",
  "Gardner Lake",
  "Gareloi Volcano",
  "Garrick's Temple to Shakespeare",
  "Garry Schyman|Schyman, Garry",
  "Gary Hooper|Hooper, Gary",
  "Gary Roberts (footballer, born 1987)",
  "Gastrotrich",
  "Gateway of India",
  "Gawsworth Old Hall",
  "Gaylussacia brachycera",
  "Gene",
  "Genetic code",
  "Genome-wide association study",
  "Geoff Horsfield|Horsfield, Geoff",
  "Geoff Smith (footballer)|Smith, Geoff",
  "Geoffroy's spider monkey",
  "Geoffroy's tamarin",
  "George Boyd (footballer)|Boyd, George",
  "George Martin|Martin, George",
  "George Schaller|Schaller, George",
  "George Toogood Smith|Smith, George Toogood",
  "Georgi Kinkladze|Kinkladze, Georgiou",
  "Georgios Samaras|Samaras, Georgios",
  "Gerald Ratner Athletics Center",
  "Gerlachovský štít",
  "Gerp's mouse lemur",
  "Gerty Cori|Cori, Gerty",
  "Ghost in the Shell (film)|Ghost in the Shell (film)",
  "Giacomo Meyerbeer|Meyerbeer, Giacomo",
  "Giant freshwater stingray",
  "Giffnock",
  "Gila monster",
  "Gilbert and Sullivan",
  "Gilberto Gil|Gil, Gilberto",
  "Gillian Welch|Welch, Gillian",
  "Girlschool",
  "Gita Gutawa|Gutawa, Gita",
  "Giuseppe Verdi|Verdi,Giuseppe",
  "Giveamanakick",
  "Gjirokastër",
  "Glacier Bay Basin",
  "Glacier Peak",
  "Gladstone, Oregon",
  "Glastonbury Tor",
  "Glastonbury",
  "Glazer ownership of Manchester United",
  "Glenrothes",
  "Gliese 581",
  "Gliese 876 b",
  "Gliese 876 c",
  "Gliese 876 d",
  "Gliese 876",
  "Gojira (band)",
  "GoldenEye",
  "Goldfinger (film)|Goldfinger (film)",
  "Goodison Park",
  "Gordon Banks|Banks, Gordon",
  "Grade I listed buildings in Somerset",
  "Graham Westley|Westley, Graham",
  "Grand Palace",
  "Grand Street Bridge (Connecticut)",
  "Grandaddy",
  "Granpa",
  "Grantham Canal",
  "Grasshopper",
  "Gray wolf",
  "Gray-tailed vole",
  "Great Barrier Reef",
  "Great Britain at the 1992 Winter Paralympics",
  "Great Britain at the 2002 Winter Paralympics",
  "Great Britain at the 2006 Winter Paralympics",
  "Great Britain at the 2008 Summer Olympics",
  "Great Britain at the 2008 Summer Paralympics",
  "Great Britain at the 2010 Winter Olympics",
  "Great Britain at the 2010 Winter Paralympics",
  "Great Moments in Aviation",
  "Great Salt Lake",
  "Great Zab",
  "Great hammerhead",
  "Great northern tilefish",
  "Great spotted kiwi",
  "Great tit",
  "Great white shark",
  "Greater adjutant",
  "Greater scaup",
  "Greater yellow-headed vulture",
  "Green Day",
  "Green Lake (Texas)",
  "Green iguana",
  "Greg Young|Young, Greg",
  "Gregorian Tower",
  "Grenada at the 2008 Summer Olympics",
  "Grevillea juniperina",
  "Grey reef shark",
  "Grey-necked rockfowl",
  "Groton Monument",
  "Gryposaurus",
  "Grévy's zebra",
  "Guianan cock-of-the-rock",
  "Guinea-Bissau women's national football team",
  "Gulf Stream",
  "Gulfton, Houston",
  "Gunnersbury Triangle",
  "Gurdon Bill Store",
  "Guto Puw",
  "Guyana at the 2008 Summer Olympics",
  "Gwyneth Herbert|Herbert, Gwyneth",
  "HAT-P-33b",
  "HD 154672 b",
  "HD 154672",
  "HD 2039",
  "HD 205739 b",
  "HD 209458 b",
  "HD 217107 b",
  "HD 217107 c",
  "HD 217107",
  "HD 28185 b",
  "HD 28185",
  "HD 40307 b",
  "HD 40307 c",
  "HD 40307 d",
  "HD 40307",
  "HIP 78530 b",
  "HIV/AIDS in Malawi",
  "Hadropithecus",
  "Haim (band)",
  "Haiti at the 2008 Summer Olympics",
  "Hale Barns",
  "Halfbeak",
  "Hampden Park",
  "Hank Williams|Williams, Hank",
  "Hard Boiled",
  "Hard Target",
  "Hardnose shark",
  "Harisu",
  "Harmondsworth Great Barn",
  "Harold Washington Cultural Center",
  "Harpy Tomb",
  "Harrisburg, Illinois",
  "Harrison County, Indiana",
  "Harry Kane|Kane, Harry",
  "Harry and the Potters",
  "Hart Lake (Oregon)",
  "Hartebeest",
  "Hartford City Courthouse Square Historic District",
  "Hartsdown Park",
  "Hatem Ben Arfa|Arfa, Hatem Ben",
  "Hayley Westenra|Westenra, Hayley",
  "Heavy Traffic",
  "Hebden, North Yorkshire",
  "Hed PE",
  "Hedonic hunger",
  "Helen Mayo|Mayo, Helen",
  "Helicoverpa zea",
  "Heller House",
  "Hellyeah",
  "Helvellyn",
  "Hemigrapsus estellinensis",
  "Hemilepistus reaumuri",
  "Henry Rollins|Rollins, Henry",
  "Herm",
  "Hermética",
  "Heterodontosauridae",
  "Hey Good Lookin' (film)|Hey Good Lookin<nowiki>'</nowiki> (film)",
  "Hibernian F.C.",
  "High Desert (Oregon)",
  "Highgrove House, Eastcote",
  "Hillel Slovak|Slovak, Hillel",
  "Hillforts in Scotland",
  "Hillingdon House",
  "Hillsboro Civic Center",
  "Hilston Park",
  "Hilton Head Island, South Carolina",
  "Hippeastrum",
  "Hipposideros besaoka",
  "Hiroki Kikuta|Kikuta, Hiroki",
  "Historic Michigan Boulevard District",
  "History of Aston Villa F.C. (1874–1961)",
  "History of Crystal Palace F.C.",
  "History of FC Barcelona",
  "History of Liverpool F.C. (1959–85)",
  "History of Liverpool F.C. (1985–present)",
  "History of Sunderland A.F.C.",
  "History of York City F.C. (1908–80)",
  "History of botany",
  "History of paleontology",
  "History of the horse in Britain",
  "Hitoshi Sakimoto|Sakimoto, Hitoshi",
  "Holliday junction",
  "Holnicote Estate",
  "Holy Rosary Cathedral (Vancouver)",
  "Homarus gammarus",
  "Homologous recombination",
  "Hong Kong",
  "Hooded crow",
  "Hoodoo Gurus",
  "Hope Solo|Solo, Hope",
  "Horn shark",
  "Horse rings in Portland, Oregon",
  "Horse",
  "Hospice care in the United States",
  "Hotel Valley Ho",
  "House (1977 film)|House (1977 film)",
  "House sparrow",
  "Housing in Scotland",
  "Howard Staunton|Staunton, Howard",
  "Howling Bells",
  "Huangshan",
  "Hud (1963 film)",
  "Hudson County Courthouse",
  "Huletts Landing, New York",
  "Hull City A.F.C.",
  "Hulme Arch Bridge",
  "Hum Aapke Hain Koun..!",
  "Human tooth",
  "Huw Edwards (conductor)|Edwards, Huw",
  "Hyacinthoides non-scripta",
  "Hyde Park Township, Cook County, Illinois",
  "Hyde Road (stadium)",
  "Hydrophiinae",
  "Hypacrosaurus",
  "Hypogeomys australis",
  "Hypsibema missouriensis",
  "Hôtel Ritz Paris",
  "Hôtel d'Alluye",
  "Ian Gillan|Gillan, Ian",
  "Ian Helliwell (footballer)|Helliwell, Ian",
  "Ian Svenonius|Svenonius, Ian",
  "Ibrox Stadium",
  "Icehouse (band)",
  "Ickenham",
  "Igbo Landing",
  "Ilaiyaraaja",
  "Illecillewaet Glacier",
  "Image Lake",
  "Imbrex and tegula",
  "Impala",
  "Ince Blundell Hall",
  "Inchdrewer Castle",
  "Inchon (film)|Inchon (film)",
  "Independence Day (1996 film)|Independence Day (1996 film)",
  "Independence Pass (Colorado)",
  "Indiana Jones and the Last Crusade",
  "Indiana Jones and the Temple of Doom",
  "Indiana State House",
  "Indigo bunting",
  "Indraloris",
  "Inon Zur|Zur, Inon",
  "Insect wing",
  "Insect",
  "Inseminoid",
  "International Association for Plant Taxonomy",
  "Invasive species",
  "Ioan Gyuri Pascu|Pascu, Gyuri",
  "Iron Maiden",
  "Ithan Creek",
  "Izak catshark",
  "JFK (film)|JFK (film)",
  "Jack Charlton|Charlton, Jack",
  "Jack Ely|Ely, Jack",
  "Jack Wall (composer)|Wall, Jack",
  "Jackie Evancho|Evancho, Jackie",
  "Jacob's Ladder (film)|Jacob's Ladder (film)",
  "Jacques Offenbach|Offenbach, Jacques",
  "Jahanpanah",
  "Jaki Byard|Byard, Jaki",
  "Jamaica at the 1988 Winter Olympics",
  "James Blunt|Blunt, James",
  "James Constable|Constable, James",
  "James Crumley (footballer)|Crumley, James",
  "James Meredith (footballer)|Meredith, James",
  "James Milner|Milner, James",
  "Jamie Stuart|Stuart, Jamie",
  "Japanese angelshark",
  "Japanese serow",
  "Jape (band)",
  "Jason Dozzell|Dozzell, Jason",
  "Java Man",
  "Jaws 2",
  "Jaws 3-D",
  "Jaws: The Revenge",
  "Jay Park|Park, Jay",
  "Jean Michel Jarre|Jarre, Jean Michel",
  "Jean de Florette",
  "Jeff Hanneman|Hanneman, Jeff",
  "Jennison Myrie-Williams|Myrie-Williams, Jennison",
  "Jenny Morris (musician)|Morris, Jenny",
  "Jeremy Soule|Soule, Jeremy",
  "Jerome, Arizona",
  "Jerry Gill|Gill, Jerry",
  "Jesper Blomqvist|Blomqvist, Jesper",
  "Jessica Mauboy|Mauboy, Jessica",
  "Jiloca (river)",
  "Jim Baxter|Baxter, Jim",
  "Jim Gannon|Gannon, Jim",
  "Jim and Mary McCartney|McCartney, Jim and Mary",
  "Jimmy Chamberlin|Chamberlin, Jimmy",
  "Jimmy Floyd Hasselbaink|Hasselbaink, Jimmy Floyd",
  "Jimmy Greaves|Greaves, Jimmy",
  "Jimmy Norman|Norman, Jimmy",
  "Jimmy Speirs|Speirs, Jimmy",
  "Jingle All the Way",
  "Job for a Cowboy",
  "Joe Colbeck|Colbeck, Joe",
  "Joe Diffie|Diffie, Joe",
  "Joel Byrom|Byrom, Joel",
  "Joey Barton|Barton, Joey",
  "Joffrey Tower",
  "Johann Strauss II|Strauss II, Johann",
  "John Benjamin Murphy|Murphy, John Benjamin",
  "John Hemmingham|Hemmingham, John",
  "John Johnson (footballer)|Johnson, John",
  "John Mousinho|Mousinho, John",
  "John Nutter|Nutter, John",
  "John Philip Sousa|Sousa, John Philip",
  "John Stainer|Stainer, John",
  "John Struthers (anatomist)|Struthers, John",
  "Johngarthia lagostoma",
  "Johnny McNichol|McNichol, Johnny",
  "Jon Challinor|Challinor, Jon",
  "Jon Coghill|Coghill, Jon",
  "Jordan Slew|Slew, Jordan",
  "Joseph F. Glidden House",
  "Joseph Widney",
  "Josh Walker|Walker, Josh",
  "Joshua King (footballer)|King, Joshua",
  "Juha Vainio|Vainio, Juha",
  "Julia Lennon|Lennon, Julia",
  "Juliomys anoblepas",
  "Junagarh Fort",
  "Juniata County, Pennsylvania",
  "Junya Nakano|Nakano, Junya",
  "Jurassic Park (film)|Jurassic Park (film)",
  "Juventus F.C.",
  "KC Stadium",
  "KMFDM",
  "Kadhalikka Neramillai",
  "Kaikhosru Shapurji Sorabji|Sorabji, Kaikhosru Shapurji",
  "Kajaani",
  "Kakha Kaladze|Kaladze, Kakha",
  "Kanye West|West, Kanye",
  "Karim Benzema|Benzema, Karim",
  "Karlheinz Stockhausen|Stockhausen, Karlheinz",
  "Karnan (film)|Karnan (film)",
  "Katie Chapman|Chapman, Katie",
  "Katie Melua|Melua, Katie",
  "Katipo",
  "Kaunas Fortress",
  "Keith Fahey|Fahey, Keith",
  "Keith Houchen|Houchen, Keith",
  "Keith Moon|Moon, Keith",
  "Kekal",
  "Kelly Rowland|Rowland, Kelly",
  "Kelvin Tan|Tan, Kelvin",
  "Ken Barnes (footballer)|Barnes, Ken",
  "Kenilworth Road",
  "Kenji Ito|Ito, Kenji",
  "Kenny McLean|McLean, Kenny",
  "Kentrosaurus",
  "Kenwood, St. George's Hill",
  "Kenwyne Jones|Jones, Kenwyne",
  "Kepler-10",
  "Kepler-10b",
  "Kepler-10c",
  "Kepler-11",
  "Kepler-11b",
  "Kepler-11c",
  "Kepler-11d",
  "Kepler-11e",
  "Kepler-11f",
  "Kepler-11g",
  "Kepler-14b",
  "Kepler-4",
  "Kepler-40",
  "Kepler-40b",
  "Kepler-4b",
  "Kepler-5",
  "Kepler-5b",
  "Kepler-6",
  "Kepler-6b",
  "Kepler-7",
  "Kepler-7b",
  "Kepler-8",
  "Kepler-8b",
  "Kepler-9",
  "Kepler-9b",
  "Kepler-9c",
  "Kepler-9d",
  "Kerry slug",
  "Kesha",
  "Kevin Nolan|Nolan, Kevin",
  "Key Biscayne",
  "Keynsham",
  "Khaplu Palace",
  "Kiger Mustang",
  "Kilham, Northumberland",
  "Killswitch Engage",
  "Kimberella",
  "King John's Hunting Lodge, Axbridge",
  "Kingdom Tower",
  "Kingston upon Hull",
  "Kingstonian F.C.",
  "Kirkcaldy",
  "Kitefin shark",
  "Kitti's hog-nosed bat",
  "Klamath River",
  "Kohala",
  "Kola Peninsula",
  "Kona Lanes",
  "Kootenay River",
  "Korn",
  "Krak des Chevaliers",
  "Kraków",
  "Krista Branch|Branch, Krista",
  "Kritosaurus",
  "Kuch Kuch Hota Hai",
  "Kumi Koda|Koda, Kumi",
  "Kvinneakt",
  "Kyle Critchell|Critchell, Kyle",
  "Kyle Nix|Nix, Kyle",
  "Kīlauea",
  "L'Enfant Plaza Hotel",
  "L.A. Takedown",
  "L.A.P.D. (band)",
  "LACM 149371",
  "La Masia",
  "La Pausa",
  "Labyrinth (film)|Labyrinth (film)",
  "Lad, A Dog (film)|Lad, A Dog (film)",
  "Lady Gaga",
  "Lafayette Afro Rock Band",
  "Lafayette Square (Buffalo)",
  "Lagidium ahuacaense",
  "Lagrivea",
  "Laguna Canyon",
  "Laguna Madre (United States)",
  "Lahore Fort",
  "Lake Burton (Antarctica)",
  "Lake Neepaulin",
  "Lake Toba",
  "Lake Untersee",
  "Lake Vostok",
  "Lake Winfield Scott",
  "Lakeshore East",
  "Lamb of God (band)",
  "Lamu Fort",
  "Lance Bass|Bass, Lance",
  "Larry Mullen, Jr.|Mullen, Larry Jr.",
  "Laserblast",
  "Lathrop House (Vassar College)",
  "Lauryn Hill|Hill, Lauryn",
  "Lavaca Bay",
  "Lawrie Wilson|Wilson, Lawrie",
  "Lawton, Oklahoma",
  "Layer Pyramid",
  "Le Dernier Combat",
  "Least weasel",
  "Lecrae",
  "Led Zeppelin",
  "Lee Hughes|Hughes, Lee",
  "Lee McEvilly|McEvilly, Lee",
  "Lee's Ferry",
  "Leicester City F.C.",
  "Leigh, Greater Manchester",
  "Lemmons",
  "Len Boyd|Boyd, Len",
  "Lena Meyer-Landrut|Meyer-Landrut, Lena",
  "Lennie Tristano|Tristano, Lennie",
  "Leo Fortune-West|Fortune-West, Leo",
  "Leopard catshark",
  "Leopard shark",
  "Leoš Janáček",
  "Lepidoptera",
  "Lerkendal Stadion",
  "Lesopoval",
  "Lesser Antillean macaw",
  "Lesser yellow-headed vulture",
  "Lesser kudu",
  "Levi Mackin|Mackin, Levi",
  "Lewisville, Texas",
  "Lhasa de Sela|Sela, de Lhasa",
  "Liam Miller|Miller, Liam",
  "Licence to Kill",
  "Lightning Bolt (band)",
  "Liliaceae",
  "Lillehammer Olympiapark",
  "Limbs of the horse",
  "Limp Bizkit",
  "Lincolnshire, Illinois",
  "Linda November|November, Linda",
  "Linfield F.C.",
  "Linkin Park",
  "Linton Park",
  "Linvoy Primus|Primus, Linvoy",
  "Linwood House",
  "Lionel Messi|Messi, Lionel",
  "Lipid bilayer",
  "Lipid",
  "Lisa Hannigan|Hannigan, Lisa",
  "Lismore, Scotland",
  "List of counties in Delaware",
  "Literary Hall",
  "Little Applegate River",
  "Little Catawissa Creek",
  "Live and Let Die (film)|Live and Let Die (film)",
  "Liverpool F.C. 4–3 Newcastle United F.C. (1996)",
  "Liverpool Town Hall",
  "Llanishen Reservoir",
  "Llantwit Major",
  "Loaded (band)",
  "Lobatus gigas",
  "London Road Fire Station, Manchester",
  "London Symphony Orchestra",
  "London",
  "London, Ontario",
  "Long Ya Men",
  "Long-billed thrasher",
  "Long-term potentiation",
  "Long-toed salamander",
  "Longfin mako shark",
  "Longtail butterfly ray",
  "Longyearbyen",
  "Loose Fur",
  "Lorde",
  "Los Ángeles Negros",
  "Louis Ngwat-Mahop|Ngwat-Mahop, Louis Clément",
  "Louisa Nécib|Nécib, Louisa",
  "Love dart",
  "Loves of a Blonde",
  "Low Fell",
  "Low-density lipoprotein receptor-related protein 8",
  "Luke Foster|Foster, Luke",
  "Lulworth skipper",
  "Lupe Fiasco|Fiasco, Lupe",
  "Lupo the Butcher",
  "Lurgan",
  "Lyme Park",
  "Lytes Cary",
  "Lāna'i hookbill",
  "M.I.A. (rapper)",
  "MOA-2009-BLG-387L",
  "MOA-2009-BLG-387Lb",
  "Macabeemyrma",
  "Machine Head (band)",
  "Madagascar women's national football team",
  "Madness (band)",
  "Madonna (entertainer)",
  "Maevia inclemens",
  "Magnapop",
  "Magnus Carlsen|Carlsen, Magnus",
  "Mahanoy Creek",
  "Mahoning Creek (Susquehanna River)",
  "Maia Estianty|Estianty, Maia",
  "Main Quad (Stanford University)",
  "Major League Soccer",
  "Mal Evans|Evans, Mal",
  "Mal Waldron|Waldron, Mal",
  "Malacostraca",
  "Malagasy hippopotamus",
  "Malawi",
  "Malaysia",
  "Malcolm Sargent|Sargent, Malcolm",
  "Malloch Building",
  "Malmö Stadion",
  "Malvern water",
  "Malvern, Worcestershire",
  "Manchester City F.C. in European football",
  "Manchester United F.C.–Arsenal F.C. brawl (1990)",
  "Mangrove whipray",
  "Manhattan",
  "Manila Hotel",
  "Manipuri pony",
  "Manor House, Sleaford",
  "Mantis",
  "Mantled guereza",
  "Mantled howler",
  "Many-banded krait",
  "Marbled electric ray",
  "Marc Overmars|Overmars, Marc",
  "Marc Pugh|Pugh, Marc",
  "Marchantiophyta",
  "Maria Radner|Radner, Maria",
  "Marine Parade Community Building",
  "Mario Balotelli|Balotelli, Mario",
  "Mark Bresciano|Bresciano, Mark",
  "Mark O. Hatfield Library",
  "Mark Roberts (footballer, born 1983)",
  "Mark Stimson|Stimson, Mark",
  "Maroon 5",
  "Marouane Chamakh|Chamakh, Marouane",
  "Marquette Building (Chicago)",
  "Mars Attacks!",
  "Marsh shrew",
  "Marshall Field and Company Building",
  "Marsileaceae",
  "Martin O'Donnell|O'Donnell, Martin",
  "Martin Peerson|Peerson, Martin",
  "Martin Ødegaard",
  "Martinique macaw",
  "Martyn Woolford|Woolford, Martyn",
  "Mary Herring|Herring, Mary",
  "Mary Seacole|Seacole, Mary",
  "Masashi Hamauzu|Hamauzu, Masashi",
  "Masonic Hall, Taunton",
  "Matagorda Bay",
  "Mathieu Valbuena|Valbuena, Mathieu",
  "Matt Jarvis|Jarvis, Matthew",
  "Matthew West|West, Matthew",
  "Mauritania at the 2004 Summer Olympics",
  "Mauritania at the 2008 Summer Olympics",
  "Mauritania at the 2012 Summer Olympics",
  "Mauritius women's national football team",
  "Max Geldray|Geldray, Max",
  "Max Weinberg|Weinberg, Max",
  "McAllister Tower Apartments",
  "McBride & the Ride",
  "McConnell Island",
  "MediaCityUK",
  "Medieval Merchant's House",
  "Megalodon",
  "Megalomys audreyae",
  "Megalosaurus",
  "Megan Rapinoe|Rapinoe, Megan",
  "Megitza",
  "Mei-Ann Chen|Chen, Mei-Ann",
  "Melly Goeslaw|Goeslaw, Melly",
  "Merced River",
  "Mercyful Fate",
  "Meridian, Mississippi",
  "Merle Hay Mall",
  "Merle Reskin Theatre",
  "Mesozoic mammals of Madagascar",
  "Messier 87",
  "Metagenomics",
  "Metanephrops challengeri",
  "Miami Valley Hospital South",
  "Michael Bostwick|Bostwick, Michael",
  "Michael Boulding|Boulding, Michael",
  "Michael Carrick|Carrick, Michael",
  "Michael Coulson (footballer)|Coulson, Michael",
  "Michael Ingham (footballer)|Ingham, Michael",
  "Michael Jackson's health and appearance",
  "Michael Jordan statue",
  "Michael Rankine|Rankine, Michael",
  "Michael Salvatori|Salvatori, Michael",
  "Michael Symes|Symes, Michael",
  "Mick Flannery|Flannery, Mick",
  "Micky Adams|Adams, Micky",
  "Microgale macpheei",
  "Middle Colonies",
  "Middlesbrough F.C.",
  "Middlesex",
  "Middleton, Leeds",
  "Middlewich",
  "Midland Football Alliance",
  "Mido (footballer)|Mido",
  "Midsomer Norton",
  "Mike Shinoda|Shinoda, Mike",
  "Milan Baroš",
  "Milford Haven",
  "Milk shark",
  "Milky Way",
  "Millepora alcicornis",
  "Millwall F.C.",
  "Millwall F.C.–West Ham United F.C. rivalry",
  "Milnrow",
  "Milwaukee Avenue Historic District",
  "Mimi Smith|Smith, Mimi",
  "Mimicry",
  "Mina (singer)|Mina",
  "Minehead",
  "Miniopterus brachytragos",
  "Miniopterus mahafaliensis",
  "Miniopterus manavi",
  "Miniopterus tao",
  "Miniopterus zapfei",
  "Missoula, Montana",
  "Missouri River",
  "Missy Higgins|Higgins, Missy",
  "Mitochondrion",
  "Mobile, Alabama",
  "Modern Benoni",
  "Mollusca",
  "Moncton",
  "Money No Enough",
  "Monifieth",
  "Mont Aiguille",
  "Montacute House",
  "Monte Testaccio",
  "Montgomery Gentry",
  "Montpelier, Brighton",
  "Montreal",
  "Moondram Pirai",
  "Moonraker (film)|Moonraker (film)",
  "Morpholino",
  "Mouna Ragam",
  "Mount Adams (Washington)",
  "Mount Bailey (Oregon)",
  "Mount Baker",
  "Mount Cleveland (Alaska)",
  "Mount Edziza volcanic complex",
  "Mount Elbert",
  "Mount Garibaldi",
  "Mount Hood",
  "Mount Jackson (Antarctica)",
  "Mount Kenya",
  "Mount Osmond, South Australia",
  "Mount Rainier",
  "Mount Redoubt",
  "Mount Tehama",
  "Mount Thielsen",
  "Mount Vesuvius",
  "Mu Arae",
  "Mu wave",
  "Mud Creek (Chillisquaque Creek)",
  "Mulan (1998 film)|Mulan (1998 film)",
  "Mulgrew Miller|Miller, Mulgrew",
  "Mullum Malarum",
  "Multiple sequence alignment",
  "Muncy Creek",
  "Mundo Perdido, Tikal",
  "Muntz Street",
  "Murano (skyscraper)",
  "Murray cod",
  "Murrays' Mills",
  "Muskrat",
  "My Bloody Valentine (band)",
  "Myco-heterotrophy",
  "Mykola Leontovych|Leontovych, Mykola",
  "Myrmecia nigrocincta",
  "Myrmeciites",
  "Mysida",
  "Mystery Train (film)|Mystery Train (film)",
  "Mystic Seaport Light",
  "Myxogastria",
  "Mérens horse",
  "NK Maribor",
  "Nadia Ali|Ali, Nadia",
  "Nailsea",
  "Black-necked spitting cobra",
  "Nani",
  "Narcissus (plant)|Narcissus",
  "Narwhal",
  "National Intercollegiate Band",
  "National Police Memorial",
  "National War Memorial (South Australia)",
  "Naulakha Pavilion",
  "Nauru at the 2008 Summer Olympics",
  "Nausicaä of the Valley of the Wind (film)",
  "Ne-Yo",
  "Nea Salamis Famagusta FC",
  "Near South Side, Chicago",
  "Neepaulakating Creek",
  "Negros fruit dove",
  "Neil Aspinall|Aspinall, Neil",
  "Neil Barrett (footballer)|Barrett, Neil",
  "Neil Peart|Peart, Neil",
  "Neil Young (footballer, born 1944)",
  "Neila Sathyalingam|Sathyalingam, Neila",
  "Nemertea",
  "Neoromicia malagasyensis",
  "Neotrypaea californiensis",
  "Nepal house martin",
  "Nepenthes rajah",
  "Nephrops norvegicus",
  "Nervous shark",
  "Nescopeck Creek",
  "Nesomys narindaensis",
  "Netherlands Antilles at the 2008 Summer Olympics",
  "Nethermost Pike",
  "Neurolinguistics",
  "Never Say Never Again",
  "Neville Southall|Southall, Neville",
  "New Brighton Tower",
  "New England Quarter",
  "New Guinea crocodile",
  "New Waveland Cafe and Clinic",
  "New York Cosmos (1970–85)",
  "New York Rescue Workers Detoxification Project",
  "New Zealand",
  "Newark, New Jersey",
  "Newcastle United F.C.",
  "Newfoundland pony",
  "Newport News, Virginia",
  "News (band)",
  "Nicki Minaj|Minaj, Nicki",
  "Nigel Gibbs|Gibbs, Nigel",
  "Niger women's national football team",
  "Night shark",
  "Nina Simone|Simone, Nina",
  "Nobuo Uematsu|Uematsu, Nobuo",
  "Noel Gallagher|Gallagher, Noel",
  "Nokomis Library",
  "Norah Head Light",
  "Norfolk, Virginia",
  "Noriko Matsueda|Matsueda, Noriko",
  "Norman Whiteside|Whiteside, Norman",
  "Norman, Oklahoma",
  "North American river otter",
  "North Shore Towers",
  "Northallerton",
  "Northern Isles",
  "Northern cardinal",
  "Northern mockingbird",
  "Notting Hill (film)|Notting Hill (film)",
  "Nude per l'assassino",
  "Nueces Bay",
  "Nuno Mendes (footballer)|Mendes, Nuno",
  "Nursehound",
  "Nyala",
  "Nycticebus kayan",
  "OSI (band)",
  "Oasis (band)",
  "Ocellated electric ray",
  "Ochetellus",
  "Octopussy",
  "Odense",
  "Oecomys sydandersoni",
  "Okapi",
  "Old Bacon Academy",
  "Old House of Keys",
  "Old Louisville",
  "Old Man of Hoy",
  "Old Tjikko",
  "Oliver Kahn|Kahn, Oliver",
  "Olympic Games ceremony",
  "Omaha, Nebraska",
  "Omak, Washington",
  "Ombla",
  "On Her Majesty's Secret Service (film)|On Her Majesty's Secret Service (film)",
  "On Your Mark",
  "One Direction",
  "One Meridian Plaza",
  "One Rincon Hill",
  "One South Broad",
  "One Times Square",
  "One World Trade Center",
  "Onefin electric ray",
  "Onion dome",
  "Opabinia",
  "Orangutan",
  "Ordsall Hall",
  "Oregon Civic Justice Center",
  "Oregon Public Library",
  "Oregon Theatre",
  "Oregon and California Railroad Revested Lands",
  "Orion Nebula",
  "Oryzomys albiventer",
  "Oryzomys nelsoni",
  "Osborne Reef",
  "Osprey",
  "Osteopathic medicine in the United States",
  "Othnielosaurus",
  "Otis Redding|Redding, Otis",
  "Oxford United F.C.",
  "Oyasato-yakata",
  "PJ Harvey|Harvey, PJ",
  "PSR B1620-26 b",
  "PSR B1937+21",
  "Pablo Ibáñez",
  "Pachycephalosaurus",
  "Pachylemur",
  "Pacific Tower (Seattle)",
  "Pacific angelshark",
  "Pacific electric ray",
  "Paco de Lucía",
  "Padayappa",
  "Palace Hotel, Perth",
  "Palak Muchhal|Muchhal, Palak",
  "Palau at the 2008 Summer Olympics",
  "Paleontology",
  "Paralympic Games",
  "Paranthodon",
  "Paratheria (mammals)",
  "Parathyroid gland",
  "Park Crescent, Brighton",
  "Paro Taktsang",
  "Parthenon Frieze",
  "Partick Thistle F.C.",
  "Partington",
  "Passer predomesticus",
  "Patagosaurus",
  "Patrice Evra|Evra, Patrice",
  "Patrick Bissell|Bissell, Patrick",
  "Patrick Kisnorbo|Kisnorbo, Patrick",
  "Patrik Berger|Berger, Patrik",
  "Patti Smith|Smith, Patti",
  "Pattie Boyd|Boyd, Pattie",
  "Paul Butterfield|Butterfield, Paul",
  "Paul Dickov|Dickov, Paul",
  "Paul Gascoigne|Gascoigne, Paul",
  "Paul Kelly (Australian musician)|Kelly, Paul",
  "Paul Oscar",
  "Paul Robinson (footballer, born 1979)",
  "Pavel Nedvěd",
  "Pavillon de Flore",
  "Pelagic stingray",
  "Pelagic thresher",
  "Pelvicachromis pulcher",
  "Penmon",
  "Pentachaeta bellidiflora",
  "Peppered maskray",
  "Perovskia atriplicifolia",
  "Perry Como|Como, Perry",
  "Personal relationships of Paul McCartney",
  "Pete Best|Best, Pete",
  "Peter Holmes|Holmes, Peter",
  "Peter Swan (footballer, born 1966)",
  "Peter Till|Till, Peter",
  "Petersen Rock Garden",
  "Petitcodiac River",
  "Petrillo Music Shell",
  "Phaeacius",
  "Phallic architecture",
  "Phedina",
  "Phengaris rebeli",
  "Phil Edwards (footballer)|Edwards, Phil",
  "Phil Ochs|Ochs, Phil",
  "Philippines",
  "Phillip Wilcher|Wilcher, Phillip",
  "Phillips Exeter Academy Library",
  "Phoronid",
  "Phumdi",
  "Pikes Hotel",
  "Pilot whale",
  "Pine Island Glacier",
  "Pink whipray",
  "Pinkan Mambo|Mambo, Pinkam",
  "Pinkham Notch",
  "Plain maskray",
  "Plant defense against herbivory",
  "Plas Mawr",
  "Pleiades",
  "Pleione (star)",
  "Plymouth",
  "Plymouth, Massachusetts",
  "Point Loma, San Diego",
  "Point Stephens Light",
  "Poison dart frog",
  "Polar bear",
  "Polish cochineal",
  "Polistes exclamans",
  "Polonnaruwa Vatadage",
  "Polyadenylation",
  "Polyclonal B cell response",
  "Pondicherry shark",
  "Pont du Gard",
  "Poole",
  "Porcelain Black|Black, Porcelain",
  "Porcupine ray",
  "Port of Liverpool Building",
  "Portia fimbriata",
  "Portia labiata",
  "Portia schultzi",
  "Portishead, Somerset",
  "Portland City Hall (Oregon)",
  "Portuguese dogfish",
  "Positive Black Soul",
  "Post Oak Mall",
  "Potamon fluviatile",
  "Potlatch River",
  "Potter-Collyer House",
  "Poulton-le-Fylde",
  "Premastication",
  "Prenton Park",
  "Presidio of Santa Barbara",
  "Prickly shark",
  "Princess Theatre (Edmonton)",
  "Prion",
  "Prionomyrmex",
  "Prior Park Landscape Garden",
  "Procellariiformes",
  "Project 86",
  "Prosaurolophus",
  "Protein C",
  "Protein",
  "Protocarnivorous plant",
  "Pryor Mountain Mustang",
  "Psycho (1960 film)|Psycho (1960 film)",
  "Psylliodes luridipennis",
  "Pteranodon",
  "Pterosaur",
  "Pudendal nerve",
  "Puerto Rico at the 2008 Summer Olympics",
  "Puffadder shyshark",
  "Pui Tak Center",
  "Pullman Square",
  "Pulteney Bridge",
  "Purple-throated cotinga",
  "Pushkar Lake",
  "Pussy Riot",
  "Pusztai affair",
  "Puthiya Paravai",
  "Pyjama shark",
  "Pyramid of Userkaf",
  "Póvoa de Varzim",
  "Qal'at al-Bahrain",
  "Quagga catshark",
  "Quatermass and the Pit (film)|Quatermass and the Pit",
  "Queen's Pier",
  "Quoll",
  "RNA thermometer",
  "RNA",
  "Radioland Murders",
  "Radstock",
  "Radyr",
  "Rage Against the Machine",
  "Raiders of the Lost Ark",
  "Rajasaurus",
  "Ralph Patt|Patt, Ralph",
  "Ramones",
  "Rancho Camulos",
  "Randolph, Tennessee",
  "Raphinae",
  "Ratu (band)",
  "Ravi Shankar|Shankar, Ravi",
  "Reading, Berkshire",
  "Real Madrid C.F.",
  "Reba McEntire|McEntire, Reba",
  "Rebbie Jackson|Jackson, Rebbie",
  "Receptor antagonist",
  "Recopa Sudamericana",
  "Reculver",
  "Recurrent laryngeal nerve",
  "Red fox",
  "Red panda",
  "Red warbler",
  "Red-headed myzomela",
  "Red-tailed hawk",
  "Red-throated loon",
  "Regency Square, Brighton",
  "Relocation of Wimbledon F.C. to Milton Keynes",
  "Renaissance Blackstone Hotel",
  "Republic of Loose",
  "Reservoir Dogs",
  "Reticulate whipray",
  "Return of the Jedi",
  "Rhondda",
  "Ricardo Arjona|Arjona, Ricardo",
  "Ricardo Rodríguez (footballer)",
  "Richard Brodie (footballer)|Brodie, Richard",
  "Richard Cresswell|Cresswell, Richard",
  "Richard D'Oyly Carte|Carte, Richard D'Oyly",
  "Richard Pacquette|Pacquette, Richard",
  "Ricki-Lee Coulter|Coulter, Ricki-Lee",
  "Rio de Janeiro bid for the 2016 Summer Olympics",
  "Rise Against",
  "Ritchie Humphreys|Humphreys, Ritchie",
  "River Arun",
  "River Avon (Bristol)",
  "River Frome, Bristol",
  "River Hull",
  "River Irwell",
  "River Oaks, Houston",
  "River Rother, East Sussex",
  "River Rother, West Sussex",
  "River Tone",
  "River Torrens",
  "River Trym",
  "River Weaver",
  "River Welland",
  "River Witham",
  "River martin",
  "Riverside and Avondale",
  "Riverview Theater",
  "Rivington",
  "Roanoke Building",
  "Robbie Fowler|Fowler, Robbie",
  "Robert Cade|Cade, Robert",
  "Robert White (Virginia physician)|White, Robert",
  "Robot Building",
  "Rochdale Town Hall",
  "Rock N Roll McDonald's",
  "Rodney Atkins|Atkins, Rodney",
  "Rodrigo (musician)",
  "Rodrigues parrot",
  "Rodrigues rail",
  "Roger Miller|Miller, Roger",
  "Roger Mowry Tavern",
  "Rohm and Haas Corporate Headquarters",
  "Roman Baths (Bath)",
  "Romeo Void",
  "Romford",
  "Ron \"Pigpen\" McKernan|McKernan, Ron \"Pigpen\"",
  "Ronnie Rocket",
  "Ronnie Wallwork|Wallwork, Ronnie",
  "Rookery Building",
  "Rory Storm|Storm, Rory",
  "Roseland Theater",
  "Rosendale Theatre",
  "Rosendale (CDP), New York",
  "Rostral migratory stream",
  "Rotating locomotion in living systems",
  "Roughtail stingray",
  "Round Hill, Brighton",
  "Round ribbontail ray",
  "Roxette",
  "Roy Paul|Paul, Roy",
  "Royal Albion Hotel",
  "Royal Philharmonic Orchestra",
  "Royal Tunbridge Wells",
  "Roystonea regia",
  "Royton",
  "Rugby union at the Summer Olympics",
  "Ruislip",
  "Ruislip-Northwood Urban District",
  "Rules of chess",
  "Runcorn",
  "Rupert D'Oyly Carte|Carte, Rupert D'Oyly",
  "Rush Street (Chicago)",
  "Russell Howarth|Howarth, Russell",
  "Rwanda women's national football team",
  "Ryan Burge|Burge, Ryan",
  "Ryan Crowther|Crowther, Ryan",
  "Ryugyong Hotel",
  "Röyksopp",
  "S Club 7",
  "S.S.C. Napoli",
  "SENSOR-Pesticides",
  "Saadanius",
  "Saido Berahino|Berahino, Saido",
  "Saint Croix macaw",
  "Saint Kitts and Nevis at the 2008 Summer Olympics",
  "Saint Lucia at the 2008 Summer Olympics",
  "Saint Paul, Minnesota",
  "Saint Vincent and the Grenadines at the 2008 Summer Olympics",
  "Sakurajima",
  "Salamander",
  "Salford, Greater Manchester",
  "Salta, Cumbria",
  "Salvia divinorum",
  "Sam Cowan|Cowan, Sam",
  "Samir Nasri|Nasri, Samir",
  "Samson Occom Bridge",
  "Samuel Hahnemann Monument",
  "San Antonio Bay",
  "San Diego",
  "San Juan Creek",
  "San Marco (Jacksonville)",
  "San Marino national football team",
  "Sanctus Real",
  "Sand Point and Middle Hope",
  "Sand whiting",
  "Sandgrouse",
  "Sands Hotel and Casino",
  "Sangay",
  "Santa Ana River",
  "Maribojoc Church",
  "Sarnia",
  "Sarus crane",
  "Saudi Arabia women's national football team",
  "Sauganash Hotel",
  "Saurolophus",
  "Sauropelta",
  "Sava",
  "Savile Row",
  "Saving Private Ryan",
  "Saw Mill River",
  "Say Anything (band)",
  "Scaly-breasted munia",
  "Scarborough, Toronto",
  "Scelidosaurus",
  "Schinderhannes (genus)",
  "Schindler's List",
  "Schlumbergera",
  "Schulze Baking Company Plant",
  "Schwester Selma",
  "Scimitar oryx",
  "Scleractinia",
  "Scotch Run (Catawissa Creek)",
  "Scotiabank Saddledome",
  "Scotland national football team manager",
  "Scotland",
  "Scott Brown (footballer, born June 1985)",
  "Scott Carson|Carson, Scott",
  "Scott Doe|Doe, Scott",
  "Scott Laird|Laird, Scott",
  "Scott Neilson (footballer)",
  "Scottish Challenge Cup",
  "Scottish castles",
  "Scream (1996 film)|Scream (1996 film)",
  "Scyllarides latus",
  "Sea of Japan naming dispute",
  "Seamount",
  "Sean Combs|Combs, Sean",
  "Sebaceous gland",
  "Seeley G. Mudd Chemistry Building",
  "Sembawang Hot Spring",
  "Senate House (University of London)",
  "Senedd",
  "Sergei Prokofiev|Prokofiev, Sergei",
  "Sergio Pellissier|Pellissier, Sergio",
  "Serpin",
  "Server Sundaram",
  "Seychelles women's national football team",
  "Seychellum",
  "Shadows Fall",
  "Shamrock Hotel",
  "Shamrock Rovers F.C.",
  "Shannon Leto|Leto, Shannon",
  "Shark",
  "Sharptooth houndshark",
  "Shaun Goater|Goater, Shaun",
  "Shaun Whalley|Whalley, Shaun",
  "Shawnee on Delaware, Pennsylvania",
  "Shay Given|Given, Shay",
  "Sheffield",
  "Sheldon Manor",
  "Shelly Manne|Manne, Shelly",
  "Shenandoah (band)",
  "Shepton Mallet",
  "Sheriff Hill",
  "Short-tail stingray",
  "Shrewsbury",
  "Sicklefin lemon shark",
  "Sicklefin weasel shark",
  "Sierra Leone at the 2004 Summer Olympics",
  "Sierra Leone at the 2012 Summer Olympics",
  "Sierra Leone women's national football team",
  "Signalling theory",
  "Silent Civilian",
  "Silver Reef, Utah",
  "Silverthrone Caldera",
  "Silvertip shark",
  "Simarouba amara",
  "Simon & Garfunkel",
  "Simon Wormull|Wormull, Simon",
  "Sinoceratops",
  "Sinosauropteryx",
  "Sir Bevil Grenville's Monument",
  "Sirex woodwasp",
  "Siri Nilsen",
  "Sisimiut",
  "Sixteen (restaurant)",
  "Skagen",
  "Skeleton at the 2010 Winter Olympics – Women's",
  "Ski jumping at the 1928 Winter Olympics",
  "Skin & Bone (film)|Skin & Bone (film)",
  "Skopje",
  "Sky Ferreira|Ferreira, Sky",
  "Slash's Snakepit",
  "Slavonia",
  "Sleaford Navigation",
  "Sleaford",
  "Sleepy Hollow (film)|Sleepy Hollow (film)",
  "Slender smooth-hound",
  "Slipknot (band)",
  "Small Mercies",
  "Small shelly fauna",
  "Smalleye hammerhead",
  "Smalltail shark",
  "Smalltooth sand tiger",
  "Smederevo Fortress",
  "Smilodon",
  "Smith-Harris House (East Lyme, Connecticut)",
  "Smithfield, London",
  "Smooth hammerhead",
  "Smooth toadfish",
  "Smoothtooth blacktip shark",
  "Snake River",
  "Snake scales",
  "Snowdon",
  "Snyder, New York",
  "Socorro springsnail",
  "Solange Knowles|Knowles, Solange",
  "Solaris (1972 film)|Solaris (1972 film)",
  "Solomon Creek",
  "Solomon Islands at the 2008 Summer Olympics",
  "Solomon Islands skink",
  "Somerhill House",
  "Somerset Coal Canal",
  "Somerton",
  "Soundgarden",
  "South Bend, Indiana",
  "South Dakota",
  "South Jordan, Utah",
  "South Park: Bigger, Longer & Uncut",
  "South Stoneham House",
  "Southampton",
  "Southern black bream",
  "Southgate, West Sussex",
  "Southworth House (Cleveland, Ohio)",
  "Spanish Hill",
  "Sparsely-spotted stingaree",
  "Species of Allosaurus|Species of Allosaurus",
  "Speed 2: Cruise Control",
  "Sperm whale",
  "Sphecius grandis",
  "Spider",
  "Spinner shark",
  "Spinosaurus",
  "Spokane, Washington",
  "Sponge",
  "Spotted eagle ray",
  "Spotted hyena",
  "Spotted sandgrouse",
  "Squatina squatina",
  "Sri Temasek",
  "St Andrew's (stadium)",
  "St Anne's Pier",
  "St John's Church, Manchester",
  "St Joseph's Convent, Taunton",
  "St Mary Redcliffe",
  "St. Boniface General Hospital (Winnipeg)",
  "St. Charles Bay",
  "St. John's, Newfoundland and Labrador",
  "Saint Peter of Alcantara Parish Church",
  "Stadium of Light",
  "Stafford L. Warren|Warren, Stafford L.",
  "Stainforth and Keadby Canal",
  "Stamford Canal",
  "Stanley Industrial Alliance Stage",
  "Stanley Matthews|Matthews, Stanley",
  "Stapes",
  "Star Trek: Insurrection",
  "Star Wars Episode I: The Phantom Menace",
  "Stargate (production team)",
  "Statue of James II, Trafalgar Square",
  "Stavesacre",
  "Steep Holm",
  "Stembridge Mill, High Ham",
  "Steuart Wilson|Wilson, Steuart",
  "Steve Morison|Morison, Steve",
  "Steve Zakuani|Zakuani, Steve",
  "Stig Inge Bjørnebye",
  "Stockport County F.C.",
  "Stoke sub Hamdon Priory",
  "Storm petrel",
  "Strang School District No. 36",
  "Street, Somerset",
  "Streeterville",
  "Stresemann's bushcrow",
  "Striped honeyeater",
  "Striptease (film)|Striptease (film)",
  "Stroma, Scotland",
  "Structural alignment",
  "Structural coloration",
  "Struthiosaurinae",
  "Stuart McCall|McCall, Stuart",
  "Stuart Milner-Barry|Milner-Barry, Stuart",
  "Stuart Sutcliffe|Sutcliffe, Stuart",
  "Stuart Tomlinson|Tomlinson, Stuart",
  "Students' Building (Vassar College)",
  "Stylidium",
  "Sublingua",
  "Sudan women's national football team",
  "Sulphur Creek (California)",
  "Sulu bleeding-heart",
  "Sum 41",
  "Sunda slow loris",
  "Sunday football in Northern Ireland",
  "Supercell (band)",
  "Superfinalen",
  "Superman (1978 film)|Superman (film)",
  "Supporters of FC Barcelona",
  "Surf Ninjas",
  "Suriname at the 2008 Summer Olympics",
  "Suspensory muscle of duodenum",
  "Sutton Court",
  "Svalbard",
  "Swakeleys House",
  "Swayamvaram",
  "Swedbank Stadion",
  "Sweet Sweetback's Baadasssss Song",
  "Swift fox",
  "Swimming at the 1980 Summer Olympics – Men's 4 × 100 metre medley relay",
  "Swimming at the 2008 Summer Olympics – Men's 100 metre butterfly",
  "Switzerland",
  "Sycamore Historic District",
  "Syd Barrett|Barrett, Syd",
  "Sydney Leroux|Leroux, Sydney",
  "Systemin",
  "São Tomé and Príncipe at the 2012 Summer Olympics",
  "TBR1",
  "TCF Bank Stadium",
  "TISM",
  "TNM 02067",
  "Tabley House",
  "Tachyoryctes rex",
  "Taipei 101",
  "Taj Mahal",
  "Takahito Eguchi|Eguchi, Takahito",
  "Taliesin (studio)",
  "Tamaraw",
  "Tameside",
  "Tank Girl (film)|Tank Girl (film)",
  "Tapeworm (band)",
  "Tarja Turunen|Turunen, Tarja",
  "Tasmanian numbfish",
  "Tasselled wobbegong",
  "Taunton",
  "Tawny nurse shark",
  "Taxiride",
  "Taxonomy of Narcissus|Taxonomy of Narcissus",
  "Taylor Swift|Swift, Taylor",
  "Team Bath F.C.",
  "Teaneck, New Jersey",
  "Telenor Arena",
  "Temnospondyli",
  "Temple of Garni",
  "Temple of the Dog",
  "Tenacious D",
  "Tennessee Walking Horse",
  "Tephrosia apollinea",
  "Terminator 2: Judgment Day",
  "Texas A&M Singing Cadets",
  "Texas",
  "Thames Valley Royals proposal",
  "The Allman Brothers Band",
  "The Amps",
  "The Beverly Hills Hotel",
  "The Big Lebowski",
  "The Black Mages",
  "The Blues Brothers (film)|The Blues Brothers (film)",
  "The Boxmasters",
  "The Byrds",
  "The Care Bears Movie",
  "The Casbah Coffee Club",
  "The Castle of Cagliostro",
  "The Chariot (band)",
  "The Cincinnati Kid",
  "The Clash",
  "The Cockroaches",
  "The Cool Kids",
  "The Crescent, Taunton",
  "The Cure",
  "The Dorchester",
  "The Doughnut",
  "The Dream (sculpture)|The Dream (sculpture)",
  "The Dykeenies",
  "The Electric Prunes",
  "The Evil Dead",
  "The Exchange, Bristol",
  "The Frighteners",
  "The George Hotel, Crawley",
  "The Get Up Kids",
  "The Haunting (1963 film)|The Haunting (1963 film)",
  "The Hudsucker Proxy",
  "The Hustler (film)|The Hustler (film)",
  "The Incredible Melting Man",
  "The Iron Giant",
  "The Jungle Book (1967 film)|The Jungle Book (1967 film)",
  "The Kentucky Headhunters",
  "The Killer (1989 film)|The Killer (1989 film)",
  "The Killers",
  "The Kingston Trio",
  "The Lion King",
  "The Little Mermaid (1989 film)|The Little Mermaid (1989 film)",
  "The Little Shop of Horrors",
  "The Living Daylights",
  "The Make-Up",
  "The Mambo Kings",
  "The Man with the Golden Gun (film)|The Man with the Golden Gun (film)",
  "The Mask of Zorro",
  "The Messenger: The Story of Joan of Arc",
  "The Nation of Ulysses",
  "The National Conference Center",
  "The Nice",
  "The Nightmare Before Christmas",
  "The Oval (Belfast)",
  "The Paperboys (Canadian band)",
  "The Prince of Egypt",
  "The Projected Man",
  "The Quarrymen",
  "The Quick and the Dead (1995 film)|The Quick and the Dead (1995 film)",
  "The Rejected",
  "The Reputation",
  "The Residences at The Ritz-Carlton (Philadelphia)",
  "The Ritz Hotel, London",
  "The Rocketeer (film)|The Rocketeer (film)",
  "The Rocky Horror Picture Show",
  "The Serpentine",
  "The Shirelles",
  "The Smeezingtons",
  "The Spy Who Loved Me (film)|The Spy Who Loved Me (film)",
  "The St. James",
  "The Sword",
  "The Teen Idles",
  "The Terminator",
  "The Texas Chain Saw Massacre",
  "The Thin Red Line (1998 film)|The Thin Red Line (1998 film)",
  "The Town That Dreaded Sundown",
  "The Tribunal, Glastonbury",
  "The Truman Show",
  "The Usual Suspects",
  "The Valley Library",
  "The Wanderers (1979 film)|The Wanderers (1979 film)",
  "The Warped Ones",
  "The White Stripes",
  "The Who",
  "The Wild Bunch",
  "The Wiz (film)|The Wiz (film)",
  "The World Is Not Enough",
  "The World of Strawberry Shortcake",
  "The X-Files (film)|The X-Files (film)",
  "Theodoxus fluviatilis",
  "Thillana Mohanambal",
  "Thin Lizzy",
  "Thirsty Merc",
  "Thirty Seconds to Mars",
  "Thomas Müller",
  "Thornback guitarfish",
  "Thorne and Hatfield Moors",
  "Three Sisters (Oregon)",
  "Thrice",
  "Thunderball (film)|Thunderball (film)",
  "Thunderbird 6",
  "Thunderbirds Are Go",
  "Thurso",
  "Tickle Cock Bridge",
  "Tiger catshark",
  "Tiger shark",
  "Tiger",
  "Tijani Babangida|Babangida, Tijani",
  "Tiktaalik",
  "Tillson Harrison|Harrison, Tillson",
  "Timbaland",
  "Timema",
  "Timor-Leste at the 2008 Summer Olympics",
  "Tina Turner|Turner, Tina",
  "Tintinhull Garden",
  "Tiny Toon Adventures: How I Spent My Vacation",
  "Titanic (1997 film)|Titanic (1997 film)",
  "Togo women's national football team",
  "Tokyo Tower",
  "Tom Araya|Araya, Tom",
  "Tommy Flanagan|Flanagan, Tommy",
  "Tommy Johnson (footballer, born 1900)",
  "Tommy Smith (footballer, born 1980)",
  "Tomorrow Never Dies",
  "Tonga at the 2008 Summer Olympics",
  "Tony Bennett|Bennett, Tony",
  "Toronto FC",
  "Tourism in Malta",
  "Tourism in Nunavut",
  "Tow Law Town F.C.",
  "Tower Building of the Little Rock Arsenal",
  "Toxin-antitoxin system",
  "Toxotes chatareus",
  "Toy Story 2",
  "Toy Story",
  "Toyota Center",
  "Trachylepis tschudii",
  "Trapalcotherium",
  "Treasurer's House",
  "Tree",
  "Trevor Pinnock|Pinnock, Trevor",
  "Triaenops goodmani",
  "Trillium grandiflorum",
  "TripleOne Somerset",
  "Trogloraptor",
  "Trout Creek Mountains",
  "Tuatara",
  "Tucker: The Man and His Dream",
  "Tufted tit-tyrant",
  "Tunicate",
  "Tupaia miocenica",
  "Turf Moor",
  "Turkey",
  "Tyldesley",
  "Tyntesfield",
  "Tyrannosauridae",
  "Tyrannosauroidea",
  "U-Drop Inn",
  "UA 8699",
  "Ullevaal Stadion",
  "Ultime grida dalla savana",
  "Underoath",
  "Unicorn (spider)|Unicorn (spider)",
  "United Kingdom national football team",
  "United States v England (1950 FIFA World Cup)",
  "United States Institute of Peace Headquarters",
  "United States at the 2008 Summer Paralympics",
  "United States",
  "University Mall (Little Rock, Arkansas)",
  "University of Michigan Men's Glee Club",
  "Upminster",
  "Upsilon Andromedae b",
  "Upsilon Andromedae c",
  "Upsilon Andromedae d",
  "Upsilon Andromedae",
  "Urmston",
  "Usher (singer)",
  "Utica, New York",
  "Utricularia inflata",
  "Uxbridge",
  "Uyarndha Manithan",
  "Valley View (Romney, West Virginia)",
  "Valley, West Virginia",
  "Van Morrison|Morrison, Van",
  "Van der Graaf Generator",
  "Vanilla Ice",
  "Vanuatu at the 2008 Summer Olympics",
  "Varanus salvadorii",
  "Velodona",
  "Velvet Revolver",
  "Velvet belly lanternshark",
  "Venues of the 2016 Winter Youth Olympics",
  "Veratalpa",
  "Vervet monkey",
  "Via della Conciliazione",
  "Vicars' Close, Wells",
  "Victor Negus|Negus, Victor",
  "Victoria Rooms, Bristol",
  "Viper dogfish",
  "Vipera berus",
  "Virgin Hotels Chicago",
  "Virgin Islands at the 2008 Summer Olympics",
  "Virgin Islands dwarf sphaero",
  "Virginia Beach, Virginia",
  "Virginia House",
  "Voalavo antsahabensis",
  "Vorontsov Palace (Alupka)",
  "Vratislav Lokvenc|Lokvenc, Vratislav",
  "Vulcanodon",
  "WASP-13",
  "WASP-13b",
  "WASP-15",
  "WASP-15b",
  "WASP-17b",
  "WASP-43",
  "WASP-43b",
  "WASP-44",
  "WASP-44b",
  "Wade Mainer|Mainer, Wade",
  "Walden Galleria",
  "Waldorf Astoria New York",
  "Waldorf–Astoria (New York, 1893)",
  "Wales Millennium Centre",
  "Wales",
  "Wall Street (1987 film)|Wall Street (1987 film)",
  "Waller Hall",
  "Wallkill Valley Rail Trail",
  "Walls of Dubrovnik",
  "Walrus",
  "Wanderers F.C.",
  "Wappocomo (Romney, West Virginia)",
  "Waptia",
  "Warburton, Greater Manchester",
  "Washington Monument",
  "Washington Park Historic District (Albany, New York)",
  "Washington Park, Chicago (community area)",
  "Waterbuck",
  "Watermill at Opwetten",
  "Watford F.C.",
  "Watson's Hotel",
  "Waylon Jennings|Jennings, Waylon",
  "Wayne Lyman Morse United States Courthouse",
  "Weh Island",
  "Wellingborough",
  "Wellington, Somerset",
  "Wells Fargo Building (Philadelphia)",
  "Wells, Somerset|Wells",
  "Werner Kaegi (composer)|Kaegi, Werner",
  "West Branch Fishing Creek",
  "West Bromwich Albion F.C.",
  "West Creek (Pennsylvania)",
  "West Ham United F.C.",
  "West Midlands (Regional) League",
  "West Pennard Court Barn",
  "West Pier",
  "West Worldham",
  "Western green mamba",
  "Westhay Moor",
  "Westholme House",
  "Westinghouse Air Brake Company General Office Building",
  "Weston-super-Mare",
  "Westonzoyland Pumping Station Museum",
  "Whale shark",
  "Whale",
  "When Harry Met Sally...",
  "Whiskery shark",
  "Whitby",
  "White Dog",
  "White Lies (band)",
  "White-eared titi",
  "White-headed capuchin",
  "White-tailed ptarmigan",
  "Whitetip reef shark",
  "Whitwell, Isle of Wight",
  "Who Framed Roger Rabbit",
  "Who's That Girl (1987 film)|Who's That Girl (1987 film)",
  "Wicked Lester",
  "Widnes",
  "Wigan",
  "Wilhelm Steinitz|Steinitz, Wilhelm",
  "Wilkins Peak",
  "William Sudell|Sudell, William",
  "Willie Irvine|Irvine, Willie",
  "Willie Nelson|Nelson, Willie",
  "Willow (film)|Willow (film)",
  "Willow Grove Park Mall",
  "Willow ptarmigan",
  "Wilsonville, Oregon",
  "Windy Nook",
  "Winghead shark",
  "Winslow Ames House",
  "Winter Olympic Games",
  "Winter Paralympic Games",
  "Wirgman Building",
  "Within the Woods",
  "Wizkid (musician)",
  "Wolf 359",
  "Wolf Point, Chicago",
  "Women's health in India",
  "Wood thrush",
  "Wood turtle",
  "Woodstock Library",
  "Wookey Hole Caves",
  "Worker policing",
  "World Chess Championship 1972",
  "World's littlest skyscraper",
  "Worsley",
  "Wrigley Square",
  "Wynton Kelly|Kelly, Wynton",
  "Wyntoon",
  "X Japan",
  "Xabi Alonso|Alonso, Xabi",
  "Yad Kennedy",
  "Yale Union Laundry Building",
  "Yamsay Mountain",
  "Yasunori Mitsuda|Mitsuda, Yasunori",
  "Yellow stingray",
  "Yellow-faced honeyeater",
  "Yemi Odubade|Odubade, Yemi",
  "Yeovil",
  "Yoann Gourcuff|Gourcuff, Yoann",
  "Yoko Ono|Ono, Yoko",
  "Yoko Shimomura|Shimomura, Yoko",
  "York",
  "You Only Live Twice (film)|You Only Live Twice (film)",
  "Youth Olympic Games",
  "Ypresiomyrma",
  "Yue Hwa Building",
  "Zanzibar red colobus",
  "Zanzibar women's national football team",
  "Zapp (band)",
  "Zarqa River",
  "Zebra shark",
  "Zennor Head",
  "Zero Patience",
  "Jane Zhang",
  "Zimbabwe",
  "Zoloti Vorota (Kiev Metro)",
  "Zombi 2",
  "Zombia",
  "Zubir Said|Said, Zubir",
  "Zygoballus sexpunctatus",
  "Zytglogge"
];
